import fs from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";

import {
  PortableCodexSecurityDossierError,
  validatePortableCodexSecurityReportCoverage,
  type PortableCandidateAssessment,
  type PortableCodexSecurityDossier,
  type PortableCoverageAnchor,
  type PortableReportArtifact,
  type PortableReportCoverageEntry,
  type PortableReportFinding,
} from "./portable-codex-security-dossier.js";

/** Small enough that a complete findings-only page fits ordinary compatible APIs. */
export const PORTABLE_CODEX_SECURITY_REPORT_SHARD_MAX_CANDIDATES = 16;

export interface PortableCodexSecurityReportShard {
  index: number;
  total: number;
  candidateIds: readonly string[];
  /** Server-owned and reduced to only confirmed candidates for this model turn. */
  dossier: PortableCodexSecurityDossier;
}

/** The only report object a model may submit for one page. Coverage remains server-owned. */
export interface PortableCodexSecurityReportShardArtifact {
  schemaVersion: 1;
  stage?: "report";
  findings: PortableReportFinding[];
}

export interface PortableCodexSecurityReportShardResult {
  shard: PortableCodexSecurityReportShard;
  /**
   * A live Portable session persists the canonical page envelope after its
   * findings-only payload has passed the pre-I/O normalizer. Pure callers may
   * still provide the raw model contract, which is materialized here too.
   */
  report: PortableCodexSecurityReportShardArtifact | PortableReportArtifact;
}

export interface PortableCodexSecurityReportShardOptions {
  /** Keeps enough model turns for one evidence request and a terminal write. */
  maxShards?: number;
}

/**
 * Partitions all confirmed candidates without dropping any. Rejected candidates
 * never consume model output: their coverage is derived from the dossier.
 */
export function createPortableCodexSecurityReportShards(
  dossier: PortableCodexSecurityDossier,
  options: PortableCodexSecurityReportShardOptions = {},
): readonly PortableCodexSecurityReportShard[] {
  const decisive = decisiveAssessments(dossier);
  const confirmed = dossier.candidates.filter((candidate) => {
    const assessment = decisive.get(candidate.id);
    if (assessment === undefined || assessment.status === "inconclusive") {
      throw new PortableCodexSecurityDossierError("candidate has no conclusive assessment");
    }
    return assessment.status === "confirmed";
  });
  // Retain the sixth visible stage even when all candidates were rejected.
  // Its empty findings artifact is still validated and final coverage is
  // deterministically generated by the server.
  const maxShards = options.maxShards === undefined
    ? Number.MAX_SAFE_INTEGER
    : Math.max(1, Math.floor(options.maxShards));
  const candidatesPerShard = PORTABLE_CODEX_SECURITY_REPORT_SHARD_MAX_CANDIDATES;
  const total = Math.max(1, Math.ceil(confirmed.length / candidatesPerShard));
  if (total > maxShards) {
    throw new PortableCodexSecurityDossierError(
      "report candidates exceed the bounded shard execution budget",
    );
  }
  return Array.from({ length: total }, (_, index) => {
    const candidates = confirmed.slice(
      index * candidatesPerShard,
      (index + 1) * candidatesPerShard,
    );
    return {
      index,
      total,
      candidateIds: candidates.map((candidate) => candidate.id),
      dossier: {
        schemaVersion: 1,
        stageSummaries: [],
        candidates: candidates.map(copyCandidate),
        assessments: candidates.map((candidate) => copyAssessment(decisive.get(candidate.id)!)),
        // The model does not author scope. This is only the page-local report
        // envelope used by the existing strict report validator.
        scope: { inspected: ["."], unexamined: [] },
      },
    };
  });
}

/**
 * Converts findings-only model output to the internal report shape before
 * artifact I/O. The existing whole-report validator then proves exact page
 * membership, one finding per confirmed id, anchors, and remediation fields.
 */
export function materializePortableCodexSecurityReportShard(
  shard: PortableCodexSecurityReportShard,
  value: unknown,
): PortableReportArtifact {
  const record = asRecord(value);
  if (
    record === null ||
    record.schemaVersion !== 1 ||
    (record.stage !== undefined && record.stage !== "report") ||
    !hasOnlyKeys(record, new Set(["schemaVersion", "stage", "findings"])) ||
    !Array.isArray(record.findings)
  ) {
    throw new PortableCodexSecurityDossierError("report shard artifact is invalid");
  }
  const coverage = shard.dossier.candidates.map((candidate) => {
    const assessment = decisiveAssessments(shard.dossier).get(candidate.id);
    if (assessment === undefined || assessment.status !== "confirmed") {
      throw new PortableCodexSecurityDossierError("report shard carries a non-confirmed candidate");
    }
    return coverageForAssessment(assessment, "reported");
  });
  const modelReport = validatePortableCodexSecurityReportCoverage({
    schemaVersion: 1,
    stage: "report",
    findings: record.findings,
    coverage: {
      inspected: shard.dossier.scope.inspected,
      unexamined: shard.dossier.scope.unexamined,
      candidates: coverage,
    },
  }, shard.dossier);
  return validatePortableCodexSecurityReportCoverage({
    ...modelReport,
    findings: modelReport.findings.map((finding) => ({
      ...finding,
      // Independent model pages commonly restart their local PCS-001 counter.
      // Candidate identity is server-owned, so make the public id stable and
      // globally unique without trusting a page-local sequence.
      id: canonicalFindingId(finding.candidateId),
    })),
  }, shard.dossier);
}

/** Combines accepted page findings with dossier-derived coverage for every candidate. */
export function assemblePortableCodexSecurityReportShards(
  dossier: PortableCodexSecurityDossier,
  results: readonly PortableCodexSecurityReportShardResult[],
): PortableReportArtifact {
  const decisive = decisiveAssessments(dossier);
  const expectedCandidateIds = dossier.candidates
    .filter((candidate) => decisive.get(candidate.id)?.status === "confirmed")
    .map((candidate) => candidate.id);
  if (results.length === 0) {
    throw new PortableCodexSecurityDossierError("report shard result count is incomplete");
  }
  const findings: PortableReportFinding[] = [];
  const ordered = [...results].sort((left, right) => left.shard.index - right.shard.index);
  for (const [index, result] of ordered.entries()) {
    if (
      result.shard.index !== index ||
      result.shard.total !== ordered.length
    ) {
      throw new PortableCodexSecurityDossierError("report shard membership is invalid");
    }
    findings.push(...validatedShardReport(result.shard, result.report).findings);
  }
  if (JSON.stringify(ordered.flatMap((result) => result.shard.candidateIds)) !== JSON.stringify(expectedCandidateIds)) {
    throw new PortableCodexSecurityDossierError("report shard membership is invalid");
  }
  const coverage = dossier.candidates.map((candidate) => {
    const assessment = decisiveAssessments(dossier).get(candidate.id);
    if (assessment === undefined || assessment.status === "inconclusive") {
      throw new PortableCodexSecurityDossierError("candidate has no conclusive assessment");
    }
    return coverageForAssessment(
      assessment,
      assessment.status === "confirmed" ? "reported" : "rejected",
    );
  });
  return validatePortableCodexSecurityReportCoverage({
    schemaVersion: 1,
    stage: "report",
    findings,
    coverage: {
      inspected: [...dossier.scope.inspected],
      unexamined: dossier.scope.unexamined.map((entry) => ({ ...entry })),
      candidates: coverage,
    },
  }, dossier);
}

function validatedShardReport(
  shard: PortableCodexSecurityReportShard,
  value: PortableCodexSecurityReportShardArtifact | PortableReportArtifact,
): PortableReportArtifact {
  if (asRecord(value)?.coverage !== undefined) {
    return validatePortableCodexSecurityReportCoverage(value, shard.dossier);
  }
  return materializePortableCodexSecurityReportShard(shard, value);
}

/** Writes only the assembled final report; page artifacts never enter Sentinel results. */
export function writePortableCodexSecurityReportShards(
  resultsDir: string,
  dossier: PortableCodexSecurityDossier,
  results: readonly PortableCodexSecurityReportShardResult[],
): PortableReportArtifact {
  const report = assemblePortableCodexSecurityReportShards(dossier, results);
  fs.mkdirSync(resultsDir, { recursive: true, mode: 0o700 });
  const target = path.join(resultsDir, "sentinel-findings.json");
  fs.writeFileSync(target, `${JSON.stringify(report)}\n`, {
    encoding: "utf8",
    mode: 0o600,
    flag: "wx",
  });
  fs.chmodSync(target, 0o600);
  return report;
}

function decisiveAssessments(
  dossier: PortableCodexSecurityDossier,
): Map<string, PortableCandidateAssessment> {
  const result = new Map<string, PortableCandidateAssessment>();
  for (const assessment of dossier.assessments) {
    if (!result.has(assessment.candidateId) || assessment.stage === "validation") {
      result.set(assessment.candidateId, assessment);
    }
  }
  return result;
}

function coverageForAssessment(
  assessment: PortableCandidateAssessment,
  disposition: PortableReportCoverageEntry["disposition"],
): PortableReportCoverageEntry {
  return {
    candidateId: assessment.candidateId,
    disposition,
    reason: assessment.reason,
    evidence: assessment.evidence.map(copyAnchor),
  };
}

function copyCandidate(candidate: PortableCodexSecurityDossier["candidates"][number]) {
  return { ...candidate, anchors: candidate.anchors.map(copyAnchor) };
}

function copyAssessment(assessment: PortableCandidateAssessment): PortableCandidateAssessment {
  return { ...assessment, evidence: assessment.evidence.map(copyAnchor) };
}

function copyAnchor(anchor: PortableCoverageAnchor): PortableCoverageAnchor {
  return { ...anchor };
}

function asRecord(value: unknown): Record<string, unknown> | null {
  return typeof value === "object" && value !== null && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

function hasOnlyKeys(value: Record<string, unknown>, allowed: ReadonlySet<string>): boolean {
  return Object.keys(value).every((key) => allowed.has(key));
}

function canonicalFindingId(candidateId: string): string {
  return `PCS-${createHash("sha256").update(candidateId, "utf8").digest("hex").slice(0, 24).toUpperCase()}`;
}
