import type { Locale } from "../../i18n";
const en = {
  title: "Snapshot file graph", description: "Explore extracted relationships in this scan’s snapshot. Connections show code structure, not proof of inspection or vulnerabilities.",
  search: "Search files", files: "Snapshot files", relations: "Directed connections", loading: "Loading snapshot graph…", error: "Could not load this scan’s graph.", retry: "Retry", unavailable: "No graph is available for this scan. Older runs or other engines may not preserve a Graphify index.",
  empty: "No files match your search.", isolated: "No extracted cross-file connections for this file.", related: "Related files", incoming: "Incoming", outgoing: "Outgoing", previous: "Previous", next: "Next", page: "Page", scope: "Selected file and its direct neighbors", select: "Select a file to explore its connections.", snapshot: "Snapshot", graph: "File relationships", count: "relationships", shown: "neighbors shown", unknown: "Snapshot identity unavailable",
};
export const filesCopy: Record<Locale, typeof en> = {
 en,
 "pt-BR": {title:"Grafo dos arquivos do snapshot",description:"Explore relações extraídas do snapshot deste scan. Conexões mostram a estrutura do código, não comprovam inspeção ou vulnerabilidades.",search:"Pesquisar arquivos",files:"Arquivos do snapshot",relations:"Conexões direcionadas",loading:"Carregando grafo do snapshot…",error:"Não foi possível carregar o grafo deste scan.",retry:"Tentar novamente",unavailable:"Este scan não tem grafo disponível. Runs antigos ou outros motores podem não preservar um índice Graphify.",empty:"Nenhum arquivo corresponde à busca.",isolated:"Nenhuma conexão extraída com outros arquivos para este arquivo.",related:"Arquivos relacionados",incoming:"Entradas",outgoing:"Saídas",previous:"Anterior",next:"Próxima",page:"Página",scope:"Arquivo selecionado e seus vizinhos diretos",select:"Selecione um arquivo para explorar suas conexões.",snapshot:"Snapshot",graph:"Relações entre arquivos",count:"relações",shown:"vizinhos exibidos",unknown:"Identidade do snapshot indisponível"},
 es:{title:"Grafo de archivos del snapshot",description:"Explora relaciones extraídas del snapshot de este scan. Las conexiones muestran estructura, no prueban inspección ni vulnerabilidades.",search:"Buscar archivos",files:"Archivos del snapshot",relations:"Conexiones dirigidas",loading:"Cargando grafo…",error:"No se pudo cargar el grafo.",retry:"Reintentar",unavailable:"Este scan no tiene un grafo disponible. Los runs antiguos u otros motores pueden no conservar un índice Graphify.",empty:"Ningún archivo coincide.",isolated:"Sin conexiones extraídas con otros archivos.",related:"Archivos relacionados",incoming:"Entradas",outgoing:"Salidas",previous:"Anterior",next:"Siguiente",page:"Página",scope:"Archivo seleccionado y vecinos directos",select:"Selecciona un archivo para explorar sus conexiones.",snapshot:"Snapshot",graph:"Relaciones entre archivos",count:"relaciones",shown:"vecinos mostrados",unknown:"Identidad del snapshot no disponible"},
 de:{title:"Dateigraph des Snapshots",description:"Extrahierte Beziehungen dieses Scan-Snapshots erkunden. Verbindungen zeigen Codestruktur, keinen Nachweis für Prüfung oder Schwachstellen.",search:"Dateien suchen",files:"Snapshot-Dateien",relations:"Gerichtete Verbindungen",loading:"Graph wird geladen…",error:"Der Graph konnte nicht geladen werden.",retry:"Erneut versuchen",unavailable:"Für diesen Scan ist kein Graph verfügbar. Ältere Läufe oder andere Engines bewahren möglicherweise keinen Graphify-Index auf.",empty:"Keine passenden Dateien.",isolated:"Keine extrahierten Verbindungen zu anderen Dateien.",related:"Verbundene Dateien",incoming:"Eingehend",outgoing:"Ausgehend",previous:"Zurück",next:"Weiter",page:"Seite",scope:"Ausgewählte Datei und direkte Nachbarn",select:"Eine Datei auswählen, um ihre Verbindungen zu erkunden.",snapshot:"Snapshot",graph:"Dateibeziehungen",count:"Beziehungen",shown:"angezeigte Nachbarn",unknown:"Snapshot-Identität nicht verfügbar"},
 fr:{title:"Graphe des fichiers du snapshot",description:"Explorez les relations extraites du snapshot de ce scan. Les connexions montrent la structure du code, sans prouver son inspection ni des vulnérabilités.",search:"Rechercher des fichiers",files:"Fichiers du snapshot",relations:"Connexions orientées",loading:"Chargement du graphe…",error:"Impossible de charger le graphe.",retry:"Réessayer",unavailable:"Aucun graphe disponible pour ce scan. Les anciens runs ou les autres moteurs peuvent ne pas conserver d’index Graphify.",empty:"Aucun fichier correspondant.",isolated:"Aucune connexion extraite vers d’autres fichiers.",related:"Fichiers liés",incoming:"Entrantes",outgoing:"Sortantes",previous:"Précédente",next:"Suivante",page:"Page",scope:"Fichier sélectionné et voisins directs",select:"Sélectionnez un fichier pour explorer ses connexions.",snapshot:"Snapshot",graph:"Relations entre fichiers",count:"relations",shown:"voisins affichés",unknown:"Identité du snapshot indisponible"},
};
